---
- name: File context inventory
  shell:
    cmd: "semanage fcontext --list -C | grep -F '{{ pattern }}'"
  failed_when: false
  changed_when: false
  register: item_record

- name: Add file context record
  command:
    cmd: semanage fcontext --add -t "{{ type }}" "{{ pattern }}"
  when: item_record.rc != 0
  register: record_add

# example entry:
# /opt/redmine-.*/log(/.*)?  all files  system_u:object_r:var_log_t:s0
- name: Modify file context record
  command:
    cmd: semanage fcontext --modify -t "{{ type }}" "{{ pattern }}"
  when: (item_record.rc == 0) and (item_record.stdout.split(":")[2] != type)
  register: record_modify

- name: Apply file context settings
  command:
    cmd: "restorecon -rv {{ path }}"
  register: restorecon_cmd
  changed_when: restorecon_cmd.stdout|length
